---
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

addons:
    apt:
        packages:
            - build-essential
            - python-dev

install:
    - pip install -r requirements.txt

script: "python setup.py flake8 test"
